[package]
name = "enr"
authors = ["Age Manning <Age@AgeManning.com>"]
edition = "2018"
version = "0.1.3"
description = "Rust implementation of Ethereum Node Record (ENR) EIP778"
readme = "./README.md"
keywords = ["ethereum", "enr", "record", "EIP778", "node"]
repository = "https://github.com/rust-ethereum/enr"
categories = ["cryptography::cryptocurrencies"]
license = "MIT"
exclude = [
	".gitignore",
	".github/*"
]

[dependencies]
base64 = "0.12.1"
bs58 = "0.3.1"
hex = "0.4.2"
log = "0.4.8"
rand = "0.7.3"
rlp = "0.4.5"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
zeroize = "1.1.0"
libsecp256k1 = { version = "0.3.5", optional = true }
ecdsa = { version = "0.7", optional = true }
sha3 = { version = "0.9", optional = true }
k256-crate = { package = "k256", version = "0.4", features = ["ecdsa"], optional = true }
serde = { version = "1.0.110", optional = true }
ed25519-dalek = { version = "1.0.0-pre.4", optional = true }
c-secp256k1 = { package = "secp256k1", version = "0.17.2", optional = true }

[dev-dependencies]
c-secp256k1 = { package = "secp256k1", features = ["rand-std"], version = "0.17.2" }

[features]
default = ["serde", "libsecp256k1" ]
ed25519 = ["ed25519-dalek"]
rust-secp256k1 = ["c-secp256k1"]
k256 = ["k256-crate", "ecdsa", "sha3"]

[lib]
name = "enr"
path = "src/lib.rs"

[package.metadata.docs.rs]
all-features = true
