name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest version of stable rust
      run: rustup update stable
    - name: Check formatting with cargofmt
      run: cargo fmt --all -- --check
  release-tests-ubuntu:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --tests
  release-tests-ubuntu-all-features:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --all-features
  release-tests-ubuntu-libsecp256k1:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --no-default-features --features "libsecp256k1" --tests
  release-tests-ubuntu-libsecp256k1-ed25519:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --no-default-features --features "libsecp256k1","ed25519" --tests
