name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest version of stable rust
      run: rustup update stable
    - name: Check formatting with cargofmt
      run: cargo fmt -- --check
  cargo-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest version of stable rust
      run: rustup update stable
    - name: Check for lint warnings
      run: cargo clippy --all-features -- -D warnings
  release-tests-ubuntu:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --tests
  release-tests-ubuntu-all-features:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --all-features
  release-tests-ubuntu-ed25519:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Run tests in release
        run: cargo test --all --release --features "ed25519" --tests
  cargo-audit:
    runs-on: ubuntu-latest
    needs: cargo-fmt
    steps:
      - uses: actions/checkout@v2
      - name: Get latest version of stable rust
        run: rustup update stable
      - name: Get latest cargo audit
        run: cargo install --force cargo-audit
      - name: Run cargo audit to identify known security vulnerabilities reported to the RustSec Advisory Database
        run: cargo audit
